FROM nginx:1.20.1

ENV NGINX_ROOT /usr/src/app/public
ENV NGINX_FPM_HOST localhost
ENV NGINX_FPM_PORT 9000

COPY /services/nginx/fpm-template.conf /etc/nginx/fpm.tmpl

RUN rm -f /etc/nginx/conf.d/default.conf
RUN rm -f /etc/nginx/nginx.conf

COPY /services/nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

COPY /services/nginx/docker-nginx.sh /usr/local/bin/docker-nginx.sh
RUN chmod +x /usr/local/bin/docker-nginx.sh

# Post build command
ENTRYPOINT ["docker-nginx.sh"]